import type { Metadata } from "next";
import {BioRhyme } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider"
import { Footer } from "@/components/footer/footer";
import { ModalProvider } from "@/components/providers/modal-provider";
import { Navbar } from "@/components/navigation/navbar";
import { cn } from "@/lib/utils";

const font = BioRhyme({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Africom Media Ltd",
  description: "Generated by Africom Media Ltd",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(font.className,"bg-gradient-to-bl from-pink-400 via-white to-blue-400")}>
       
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
          
          
          >
             <ModalProvider />
            <Navbar />
            {children}
            <Footer />
          </ThemeProvider>
        
        </body>
    </html>
  );
}
